import { Itinerary } from "@/types/travel";

export const mockItinerary: Itinerary = {
  itinerary_id: "mock-001",
  title: "Khám phá Đà Lạt 3 ngày 2 đêm",
  destination: "Đà Lạt, Lâm Đồng, Việt Nam",
  start_date: "2026-05-01",
  end_date: "2026-05-03",
  summary:
    "Lịch trình khám phá Đà Lạt với focus vào cà phê, thiên nhiên và ẩm thực địa phương.",
  budget: {
    total_estimated: 4500000,
    currency: "VND",
    breakdown: {
      accommodation: 1200000,
      transport: 800000,
      food: 1500000,
      activities: 700000,
      misc: 300000,
    },
  },
  days: [
    {
      day: 1,
      date: "2026-05-01",
      theme: "Đến nơi, khám phá trung tâm",
      activities: [
        {
          id: "act-001",
          time: "07:30",
          duration_minutes: 90,
          type: "transport",
          title: "Bay từ Hà Nội đến Đà Lạt",
          description:
            "Chuyến bay VJ123 Nội Bài → Liên Khương. Đặt trước để có giá tốt.",
          location: {
            name: "Sân bay Nội Bài",
            address: "Phú Minh, Sóc Sơn, Hà Nội",
            lat: 21.2187,
            lng: 105.8037,
          },
          cost_estimate: 800000,
          tips: "Check-in online 24h trước để chọn ghế cửa sổ",
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["flight", "transport"],
          is_locked: true,
        },
        {
          id: "act-002",
          time: "12:00",
          duration_minutes: 60,
          type: "food",
          title: "Cơm chiều tại Quán Cô Ba",
          description:
            "Quán cơm bình dân nổi tiếng người Đà Lạt, phục vụ các món ăn truyền thống.",
          location: {
            name: "Quán Cô Ba",
            address: "5 Phan Đình Phùng, Đà Lạt",
            lat: 11.9404,
            lng: 108.4452,
          },
          cost_estimate: 80000,
          tips: "Thử canh bí đỏ và cá kho tộ",
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["lunch", "local-food"],
        },
        {
          id: "act-003",
          time: "14:00",
          duration_minutes: 120,
          type: "activity",
          title: "Hồ Xuân Hương",
          description:
            "Hồ nước ngọt nhân tạo nằm giữa trung tâm thành phố, lý tưởng để đi dạo và chụp ảnh.",
          location: {
            name: "Hồ Xuân Hương",
            address: "Trung tâm Đà Lạt",
            lat: 11.9364,
            lng: 108.4378,
          },
          cost_estimate: 0,
          is_hidden_gem: false,
          weather_sensitive: true,
          tags: ["sightseeing", "walking"],
          image_url:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/H%E1%BB%93_Xu%C3%A2n_H%C6%B0%C6%A1ng.jpg/1200px-H%E1%BB%93_Xu%C3%A2n_H%C6%B0%C6%A1ng.jpg",
        },
        {
          id: "act-004",
          time: "18:00",
          duration_minutes: 90,
          type: "food",
          title: "Chợ Đêm Đà Lạt",
          description:
            "Khám phá chợ đêm nổi tiếng với bánh tráng nướng, bắp nướng và các đặc sản địa phương.",
          location: {
            name: "Chợ Đêm Đà Lạt",
            address: "Nguyễn Thị Minh Khai, Đà Lạt",
            lat: 11.9415,
            lng: 108.4426,
          },
          cost_estimate: 150000,
          tips: "Thử nem nướng và sữa đậu nành nóng",
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["night-market", "street-food"],
        },
      ],
    },
    {
      day: 2,
      date: "2026-05-02",
      theme: "Thiên nhiên & Thác nước",
      activities: [
        {
          id: "act-005",
          time: "07:00",
          duration_minutes: 60,
          type: "food",
          title: "Sáng tại The Married Beans",
          description:
            "Cà phê specialty nổi tiếng ở Đà Lạt, view rừng thông cực đẹp.",
          location: {
            name: "The Married Beans",
            address: "Đường Hùng Vương, Đà Lạt",
            lat: 11.9421,
            lng: 108.4388,
          },
          cost_estimate: 65000,
          tips: "Đến sớm để có bàn ngoài trời đẹp nhất",
          is_hidden_gem: true,
          weather_sensitive: false,
          tags: ["coffee", "breakfast", "specialty-coffee"],
        },
        {
          id: "act-006",
          time: "09:00",
          duration_minutes: 180,
          type: "activity",
          title: "Thác Datanla",
          description:
            "Thác nước đẹp cách trung tâm 5km. Có trò chơi mạo hiểm như ống trượt.",
          location: {
            name: "Thác Datanla",
            address: "Quốc lộ 20, Đà Lạt",
            lat: 11.9068,
            lng: 108.4372,
          },
          cost_estimate: 150000,
          tips: "Mang giày chống trượt, trời thường mát vào buổi sáng",
          is_hidden_gem: false,
          weather_sensitive: true,
          tags: ["waterfall", "outdoor", "adventure"],
        },
        {
          id: "act-007",
          time: "14:00",
          duration_minutes: 120,
          type: "activity",
          title: "Vườn Rau Là Nhà",
          description:
            "Trang trại hữu cơ ẩn mình trong thung lũng, ít du khách biết đến. Trải nghiệm hái rau.",
          location: {
            name: "Vườn Rau Là Nhà",
            address: "Thung lũng Tà Nung, Đà Lạt",
            lat: 11.8901,
            lng: 108.3982,
          },
          cost_estimate: 80000,
          tips: "Đặt lịch trước qua Zalo, ăn trưa tại vườn rất ngon",
          is_hidden_gem: true,
          weather_sensitive: false,
          tags: ["farm", "hidden-gem", "organic"],
        },
        {
          id: "act-008",
          time: "19:00",
          duration_minutes: 90,
          type: "food",
          title: "Nhà hàng Minh Toan",
          description:
            "Nhà hàng lâu đời phục vụ lẩu bò Đà Lạt và các món nướng trứ danh.",
          location: {
            name: "Nhà hàng Minh Toan",
            address: "48 Hai Bà Trưng, Đà Lạt",
            lat: 11.9432,
            lng: 108.4419,
          },
          cost_estimate: 200000,
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["dinner", "hot-pot", "local"],
        },
      ],
    },
    {
      day: 3,
      date: "2026-05-03",
      theme: "Làng nghề & Bay về",
      activities: [
        {
          id: "act-009",
          time: "08:00",
          duration_minutes: 120,
          type: "activity",
          title: "Làng Cù Lần",
          description:
            "Làng dân tộc K'Ho bảo tồn văn hóa truyền thống. Cảnh quan núi rừng tuyệt đẹp.",
          location: {
            name: "Làng Cù Lần",
            address: "Lạc Dương, Đà Lạt",
            lat: 12.0456,
            lng: 108.3901,
          },
          cost_estimate: 100000,
          is_hidden_gem: true,
          weather_sensitive: false,
          tags: ["culture", "village", "hidden-gem"],
        },
        {
          id: "act-010",
          time: "11:00",
          duration_minutes: 60,
          type: "shopping",
          title: "Mua đặc sản về",
          description:
            "Mua trà atiso, dâu tây, mứt hoa quả tại Chợ Đà Lạt làm quà.",
          location: {
            name: "Chợ Đà Lạt",
            address: "Nguyễn Thị Minh Khai, Đà Lạt",
            lat: 11.9415,
            lng: 108.4426,
          },
          cost_estimate: 300000,
          tips: "Trả giá là chuyện bình thường tại chợ",
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["shopping", "souvenir"],
        },
        {
          id: "act-011",
          time: "15:00",
          duration_minutes: 90,
          type: "transport",
          title: "Bay về Hà Nội",
          description: "Chuyến bay VJ456 Liên Khương → Nội Bài.",
          location: {
            name: "Sân bay Liên Khương",
            address: "Liên Nghĩa, Đức Trọng, Lâm Đồng",
            lat: 11.7503,
            lng: 108.3833,
          },
          cost_estimate: 800000,
          is_hidden_gem: false,
          weather_sensitive: false,
          tags: ["flight", "transport"],
          is_locked: true,
        },
      ],
    },
  ],
  hidden_gems: [
    {
      id: "gem-001",
      name: "Cà phê Tà Nung",
      description:
        "Quán cà phê giữa rừng thông, view núi đẹp mê hồn, ít du khách biết",
      location: {
        name: "Cà phê Tà Nung",
        lat: 11.8923,
        lng: 108.4012,
      },
      source: "Tavily search",
      confidence_score: 0.87,
    },
    {
      id: "gem-002",
      name: "Vườn Rau Là Nhà",
      description:
        "Trang trại hữu cơ trong thung lũng yên tĩnh, trải nghiệm đồng quê",
      location: {
        name: "Vườn Rau Là Nhà",
        lat: 11.8901,
        lng: 108.3982,
      },
      source: "Tavily search",
      confidence_score: 0.91,
    },
  ],
  meta: {
    generated_by: "planner_agent_v1",
    model_used: "gemini-1.5-pro",
    generated_at: new Date().toISOString(),
    version: 1,
  },
};
